<a href="https://colab.research.google.com/github/DajanaSanchez/BirdMigrationClimateAnalysis/blob/main/merge_example_rob_20250213.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import drive
drive.mount('/content/drive/')

Mounted at /content/drive/

In [2]:
%cd '/content/drive/MyDrive/Colab Notebooks/IT Capstone'

%ls -ltra *parquet

/content/drive/MyDrive/Colab Notebooks/IT Capstone
-rw------- 1 root root 4664523745 Jan 30 02:59 checklists_big.parquet
-rw------- 1 root root  122148233 Jan 31 15:16 checklists.parquet
-rw------- 1 root root  544244928 Jan 31 21:42 combined_checklists.parquet
-rw------- 1 root root   48381471 Jan 31 21:43 sabina.parquet
-rw------- 1 root root    8643996 Feb 14 03:25 climate_merged_final.parquet

In [10]:
import pandas as pd

# File path (update this with your actual path)
file_path = 'sabina.parquet'  # Change this if needed

# Read the Parquet file
df = pd.read_parquet(file_path)

# Extract the first 10 records
df_head = df.head(1)

# Save the extracted records to a new Parquet file
output_file = '/content/drive/My Drive/sabina_first_10.parquet'  # Change as needed
df_head.to_parquet(output_file, index=False)

print(f"First 10 records saved to {output_file}")

First 10 records saved to /content/drive/My Drive/sabina_first_10.parquet

In [11]:
display(df_head)

    LATITUDE   LONGITUDE OBSERVATION DATE
0  32.045333 -115.908508          1995-11

In [12]:
# File path (update this with your actual path)
file_path = 'climate_merged_final.parquet'  # Change this if needed

# Read the Parquet file
df = pd.read_parquet(file_path)

# Extract the first 10 records
df_head = df.head(10)

# Display all 10 records
from IPython.display import display
display(df_head)

,Station_ID,Date,Latitude,Longitude,Elevation,State,StationName,Temp_celsius,Precip_mm,TempFlags,Precip_MeasurementFlag,Precip_QCFlag,Precip_SourceFlag,Precip_SourceIndex,Precip_FirstYear,Precip_LastYear
0,CA001011500,1961-01,48.9333,-123.75,75.0,None,BC CHEMAINUS,5.01,372.3,E,None,None,D,23584.0,1919,2024
1,CA001011500,1962-01,48.9333,-123.75,75.0,None,BC CHEMAINUS,3.53,107.4,E,None,None,D,23584.0,1919,2024
2,CA001011500,1963-01,48.9333,-123.75,75.0,None,BC CHEMAINUS,1.55,33.5,E,None,None,D,23584.0,1919,2024
3,CA001011500,1964-01,48.9333,-123.75,75.0,None,BC CHEMAINUS,4.56,302.5,E,None,None,D,23584.0,1919,2024
4,CA001011500,1965-01,48.9333,-123.75,75.0,None,BC CHEMAINUS,2.73,169.4,E,None,None,D,23584.0,1919,2024
5,CA001011500,1966-01,48.9333,-123.75,75.0,None,BC CHEMAINUS,3.28,256.2,E,None,None,D,23584.0,1919,2024
6,CA001011500,1967-01,48.9333,-123.75,75.0,None,BC CHEMAINUS,4.60,328.5,E,None,None,D,23584.0,1919,2024
7,CA001011500,1968-01,48.9333,-123.75,75.0,None,BC CHEMAINUS,3.30,356.1,E,None,None,D,23584.0,1919,2024
8,CA001011500,1969-01,48.9333,-123.75,75.0,None,BC CHEMAINUS,-1.80,123.4,E,None,None,D,23584.0,1919,2024
9,CA001011500,1970-01,48.9333,-123.75,75.0,None,BC CHEMAINUS,3.62,173.1,E,None,None,D,23584.0,1919,2024

In [15]:
!pip install duckdb

Requirement already satisfied: duckdb in /usr/local/lib/python3.11/dist-packages (1.1.3)

In [19]:
import duckdb
import pandas as pd

# File path (update as needed)
sabina_file = 'sabina.parquet'
sabina_reduced_file = 'sabina_reduced.parquet'  # New file with only 2 records

# Read only the first 2 records from the original file
df_sabina = pd.read_parquet(sabina_file).head(2)

# Save the reduced file
df_sabina.to_parquet(sabina_reduced_file, index=False)

# Connect to DuckDB and load the reduced file
con = duckdb.connect()
df_duckdb = con.execute(f"SELECT * FROM read_parquet('{sabina_reduced_file}')").df()

# Display the loaded records
print(df_duckdb)

    LATITUDE   LONGITUDE OBSERVATION DATE
0  32.045333 -115.908508          1995-11
1  30.409449 -115.945759          1998-03

In [20]:
import duckdb

# File path (update as needed)
climate_file = 'climate_merged_final.parquet'

# Connect to DuckDB and load the file
con = duckdb.connect()
df_climate = con.execute(f"SELECT * FROM read_parquet('{climate_file}')").df()

# Display the first 10 records
print(df_climate.head(10))

    Station_ID     Date  Latitude  Longitude  Elevation State   StationName  \
0  CA001011500  1961-01   48.9333    -123.75       75.0  None  BC CHEMAINUS
1  CA001011500  1962-01   48.9333    -123.75       75.0  None  BC CHEMAINUS
2  CA001011500  1963-01   48.9333    -123.75       75.0  None  BC CHEMAINUS
3  CA001011500  1964-01   48.9333    -123.75       75.0  None  BC CHEMAINUS
4  CA001011500  1965-01   48.9333    -123.75       75.0  None  BC CHEMAINUS
5  CA001011500  1966-01   48.9333    -123.75       75.0  None  BC CHEMAINUS
6  CA001011500  1967-01   48.9333    -123.75       75.0  None  BC CHEMAINUS
7  CA001011500  1968-01   48.9333    -123.75       75.0  None  BC CHEMAINUS
8  CA001011500  1969-01   48.9333    -123.75       75.0  None  BC CHEMAINUS
9  CA001011500  1970-01   48.9333    -123.75       75.0  None  BC CHEMAINUS

   Temp_celsius  Precip_mm TempFlags Precip_MeasurementFlag Precip_QCFlag  \
0          5.01      372.3         E                   None          None
1          3.53      107.4         E                   None          None
2          1.55       33.5         E                   None          None
3          4.56      302.5         E                   None          None
4          2.73      169.4         E                   None          None
5          3.28      256.2         E                   None          None
6          4.60      328.5         E                   None          None
7          3.30      356.1         E                   None          None
8         -1.80      123.4         E                   None          None
9          3.62      173.1         E                   None          None

  Precip_SourceFlag  Precip_SourceIndex  Precip_FirstYear  Precip_LastYear
0                 D             23584.0              1919             2024
1                 D             23584.0              1919             2024
2                 D             23584.0              1919             2024
3                 D             23584.0              1919             2024
4                 D             23584.0              1919             2024
5                 D             23584.0              1919             2024
6                 D             23584.0              1919             2024
7                 D             23584.0              1919             2024
8                 D             23584.0              1919             2024
9                 D             23584.0              1919             2024

In [32]:
import duckdb

# File paths (update as needed)
sabina_file = 'sabina_reduced.parquet'  # Reduced file with 2 records
climate_file = 'climate_merged_final.parquet'

# Connect to DuckDB
con = duckdb.connect()

# Perform INNER JOIN on date fields
query = f"""
    SELECT sab.*,cli.latitude,cli.longitude,cli.elevation
    FROM read_parquet('{sabina_file}') AS sab
    INNER JOIN read_parquet('{climate_file}') AS cli
    ON sab."OBSERVATION DATE" = cli.Date
"""

# Execute the query and store result in a Pandas DataFrame
df_merged = con.execute(query).df()

# Display the merged records
print(df_merged)

       LATITUDE   LONGITUDE OBSERVATION DATE  Latitude_1  Longitude_1  \
0     32.045333 -115.908508          1995-11     48.9333    -123.7500
1     32.045333 -115.908508          1995-11     48.7167    -123.5500
2     32.045333 -115.908508          1995-11     48.8167    -124.1333
3     32.045333 -115.908508          1995-11     48.8333    -124.0500
4     32.045333 -115.908508          1995-11     48.7333    -123.7333
...         ...         ...              ...         ...          ...
5039  32.045333 -115.908508          1995-11     32.7333     -96.9667
5040  32.045333 -115.908508          1995-11     34.8825     -95.7817
5041  32.045333 -115.908508          1995-11     36.0103     -94.1683
5042  32.045333 -115.908508          1995-11     38.6803    -104.7639
5043  32.045333 -115.908508          1995-11     40.8589     -74.0561

      Elevation
0          75.0
1           1.0
2         177.0
3         171.0
4         103.0
...         ...
5039      150.0
5040      229.5
5041      377.0
5042     1780.6
5043        0.9

[5044 rows x 6 columns]

In [38]:
import duckdb

# File paths (update as needed)
sabina_file = 'sabina_reduced.parquet'  # Reduced file with 2 records
climate_file = 'climate_merged_final.parquet'

# Connect to DuckDB
con = duckdb.connect()

# Perform INNER JOIN on first two characters of Latitude + OBSERVATION DATE
query = f"""
    SELECT sab.*, cli.Latitude, cli.Longitude, cli.Elevation
    FROM (
        SELECT *, LEFT(CAST(LATITUDE AS VARCHAR), 4) AS lat_prefix
        FROM read_parquet('{sabina_file}')
        LIMIT 1
    ) AS sab
    INNER JOIN (
        SELECT *, LEFT(CAST(Latitude AS VARCHAR), 4) AS lat_prefix
        FROM read_parquet('{climate_file}')
    ) AS cli
    ON sab."OBSERVATION DATE" = cli.Date
    AND sab.lat_prefix = cli.lat_prefix
"""

# Execute the query and store result in a Pandas DataFrame
df_merged = con.execute(query).df()

# Display the merged records
print(df_merged)

    LATITUDE   LONGITUDE OBSERVATION DATE lat_prefix  Latitude_1  Longitude_1  \
0  32.045333 -115.908508          1995-11       32.0     32.0711     -93.7589

   Elevation
0       98.1

In [55]:
import duckdb

# File path (update as needed)
climate_file = 'climate_merged_final.parquet'

# Connect to DuckDB
con = duckdb.connect()

# Query to search for Latitude and Longitude starting with "32" and "-115"
query = f"""
    SELECT DISTINCT Longitude
    FROM read_parquet('{climate_file}')
    WHERE CAST(Latitude AS VARCHAR) LIKE '32.%'
    AND CAST(Longitude AS VARCHAR) LIKE '-115.9%'
"""

# Execute the query and store the result in a Pandas DataFrame
df_result = con.execute(query).df()

# Display the search results
print(df_result)

Empty DataFrame
Columns: [Longitude]
Index: []

In [56]:
import duckdb

# File paths (update as needed)
sabina_file = 'sabina_reduced.parquet'  # Reduced file with 2 records
climate_file = 'climate_merged_final.parquet'

# Connect to DuckDB
con = duckdb.connect()

# Query to join Sabina with the closest Climate Latitude & Longitude
query = f"""
    WITH RankedMatches AS (
        SELECT
            sab.*,
            cli.Latitude AS Climate_Latitude,
            cli.Longitude AS Climate_Longitude,
            cli.Elevation,
            ABS(sab.LATITUDE - cli.Latitude) + ABS(sab.LONGITUDE - cli.Longitude) AS distance,
            ROW_NUMBER() OVER (
                PARTITION BY sab.LATITUDE, sab.LONGITUDE, sab."OBSERVATION DATE"
                ORDER BY ABS(sab.LATITUDE - cli.Latitude) + ABS(sab.LONGITUDE - cli.Longitude) ASC
            ) AS rank
        FROM read_parquet('{sabina_file}') AS sab
        LEFT JOIN read_parquet('{climate_file}') AS cli
        ON sab."OBSERVATION DATE" = cli.Date
    )
    SELECT * FROM RankedMatches WHERE rank = 1
"""

# Execute the query and store result in a Pandas DataFrame
df_merged = con.execute(query).df()

# Display the merged records
print(df_merged)

    LATITUDE   LONGITUDE OBSERVATION DATE  Climate_Latitude  \
0  30.409449 -115.945759          1998-03           32.8325
1  32.045333 -115.908508          1995-11           32.4000

   Climate_Longitude  Elevation  distance  rank
0          -115.6639      -14.0  2.704909     1
1          -115.1833       11.3  1.079875     1